# Site settings
title: Terrafilosofica
email: a.velj@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website. I am philosopher interested in webdesign, photography, media...
baseurl: "https://terraphilosofica.github.io/" # the subpath of your site, e.g. /blog/
url: "http://aleksandraveljkovic.netlify.com" # the base hostname & protocol for your site
twitter_username: terrafilosofica
github_username:  terraphilosofica

# Build settings
markdown: kramdown

theme: jekyll-theme-hacker
